version: "3.9"
services:
  kampuscu-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FIREBASE_CREDENTIALS_PATH=/app/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json
    volumes:
      - ./Presentation/API/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json:/app/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json
    expose:
      - "5000"
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kampuscu-api