version: "3.9"
services:
  kampuscu-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FIREBASE_CREDENTIALS_PATH=/app/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json
    volumes:
      - ./Presentation/API/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json:/app/kampuscu-6c1ae-firebase-adminsdk-fbsvc-56d05a892b.json