// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(KampusCUContext))]
    [Migration("20250110091053_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.ClubManagements.Club", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("GidCategoryFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GidManagerFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Gid");

                    b.HasIndex("GidCategoryFK");

                    b.HasIndex("GidManagerFK");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Announcement", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("GidAnnouncementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GidClubFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GidUserFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.HasKey("Gid");

                    b.HasIndex("GidAnnouncementType");

                    b.HasIndex("GidClubFK");

                    b.HasIndex("GidUserFK");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Calendar", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<Guid>("GidEventFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Gid");

                    b.HasIndex("GidEventFK");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Event", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EventStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("GidClubFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Gid");

                    b.HasIndex("GidClubFK");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.AnnouncementType", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Gid");

                    b.ToTable("AnnouncementTypes");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Category", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Gid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Class", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Gid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Department", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Gid");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.GeneralManagements.Admin", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Gid");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Domain.Entities.GeneralManagements.User", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataState")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("GidClassFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GidDepartmentFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsBloodDonor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Gid");

                    b.HasIndex("GidClassFK");

                    b.HasIndex("GidDepartmentFK");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.ClubManagements.Club", b =>
                {
                    b.HasOne("Domain.Entities.DefinitionManagements.Category", "CategoryFK")
                        .WithMany("Clubs")
                        .HasForeignKey("GidCategoryFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.GeneralManagements.User", "UserFK")
                        .WithMany("Clubs")
                        .HasForeignKey("GidManagerFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoryFK");

                    b.Navigation("UserFK");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Announcement", b =>
                {
                    b.HasOne("Domain.Entities.DefinitionManagements.AnnouncementType", "AnnouncementTypeFK")
                        .WithMany("Announcements")
                        .HasForeignKey("GidAnnouncementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ClubManagements.Club", "ClubFK")
                        .WithMany("Announcements")
                        .HasForeignKey("GidClubFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.GeneralManagements.User", "UserFK")
                        .WithMany("Announcements")
                        .HasForeignKey("GidUserFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnnouncementTypeFK");

                    b.Navigation("ClubFK");

                    b.Navigation("UserFK");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Calendar", b =>
                {
                    b.HasOne("Domain.Entities.CommunicationManagements.Event", "EventFK")
                        .WithMany("Calendars")
                        .HasForeignKey("GidEventFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventFK");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Event", b =>
                {
                    b.HasOne("Domain.Entities.ClubManagements.Club", "ClubFK")
                        .WithMany("Events")
                        .HasForeignKey("GidClubFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClubFK");
                });

            modelBuilder.Entity("Domain.Entities.GeneralManagements.User", b =>
                {
                    b.HasOne("Domain.Entities.DefinitionManagements.Class", "ClassFK")
                        .WithMany("Users")
                        .HasForeignKey("GidClassFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.DefinitionManagements.Department", "DepartmentFK")
                        .WithMany("Users")
                        .HasForeignKey("GidDepartmentFK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassFK");

                    b.Navigation("DepartmentFK");
                });

            modelBuilder.Entity("Domain.Entities.ClubManagements.Club", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Domain.Entities.CommunicationManagements.Event", b =>
                {
                    b.Navigation("Calendars");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.AnnouncementType", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Category", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Class", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.DefinitionManagements.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.GeneralManagements.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
